version: '3'
services:
    game:
        build: '../game'
        image: 'mcgame'
        ports: 
            - '8080:8080'
            - '25565:25565'
        volumes:
            - './gamedata/:/gamedata'
        depends_on:
            - 'mapsync'

    mapsync:
        build: '../mapsync'
        image: 'mapsync_game'
        volumes:
            - './gamedata:/gamedata:ro'
